const products = {
    avion : {
        nom : "Avion",
        img : "avion.webp",
        nomCreator : "DUPONT Jean",
        nbPieces : "345",
        price : "32",
        fav : false,
    },
    dinosaure : {
        nom : "Dinosaure",
        img : "dinosaure.webp",
        nomCreator : "Durant Fabien",
        nbPieces : "253",
        price : "15",
        fav : true,
    },
    dragon : {
        nom : "Dragon",
        img : "dragon.webp",
        nomCreator : "BICHON Lucas",
        nbPieces : "123",
        price : "12",
        fav : false,
    },
    girafe : {
        nom : "Girafe",
        img : "girafe.jpg",
        nomCreator : "BOULANGER Hugo",
        nbPieces : "475",
        price : "45",
        fav : false,
    },
    lapin : {
        nom : "Lapin",
        img : "lapin.webp",
        nomCreator : "CLEMENT Martin",
        nbPieces : "172",
        price : "16",
        fav : false,
    },
    licorne : {
        nom : "Licorne",
        img : "licorne.jpg",
        nomCreator : "DUJARDIN Clement",
        nbPieces : "195",
        price : "20",
        fav : true,
    },
    maison : {
        nom : "Maison",
        img : "maison.webp",
        nomCreator : "DUPONT Martine",
        nbPieces : "535",
        price : "45",
        fav : false,
    },
    moto : {
        nom : "Moto",
        img : "moto.webp",
        nomCreator : "DUPONT Jeanne",
        nbPieces : "315",
        price : "30",
        fav : true,
    },
    navette : {
        nom : "Navette",
        img : "navette.webp",
        nomCreator : "DUPONT Lucie",
        nbPieces : "280",
        price : "28",
        fav : false,
    },
    perroquet : {
        nom : "Perroquet",
        img : "perroquet.webp",
        nomCreator : "LONCHAMPS Elize",
        nbPieces : "275",
        price : "25",
        fav : false,
    },
    renard : {
        nom : "Renard",
        img : "renard.jpg",
        nomCreator : "DEVAL Victor",
        nbPieces : "132",
        price : "12",
        fav : false,
    },
    tigre : {
        nom : "Tigre",
        img : "tigre.webp",
        nomCreator : "DUPRES Elodie",
        nbPieces : "124",
        price : "12",
        fav : false,
    },
};