const products = {
    avion: {
        nom: "Avion",
        img: "avion.webp",
        nomCreator: "DUPONT Jean",
        nbPieces: "345",
        price: "32",
        fav: false,
    },
    dinosaure: {
        nom: "Dinosaure",
        img: "dinosaure.webp",
        nomCreator: "MARTIN Luc",
        nbPieces: "200",
        price: "22",
        fav: true,
    },
    dragon: {
        nom: "Dragon",
        img: "dragon.webp",
        nomCreator: "GIRARD Marie",
        nbPieces: "500",
        price: "45",
        fav: false,
    },
    girafe: {
        nom: "Girafe",
        img: "girafe.jpg",
        nomCreator: "LEGRAND Pierre",
        nbPieces: "150",
        price: "18",
        fav: false,
    },
    lapin: {
        nom: "Lapin",
        img: "lapin.webp",
        nomCreator: "DAVID Claire",
        nbPieces: "120",
        price: "15",
        fav: true,
    },
    licorne: {
        nom: "Licorne",
        img: "licorne.jpg",
        nomCreator: "DUPREZ Jules",
        nbPieces: "300",
        price: "30",
        fav: false,
    },
    maison: {
        nom: "Maison",
        img: "maison.webp",
        nomCreator: "BONNET Louise",
        nbPieces: "600",
        price: "50",
        fav: false,
    },
    moto: {
        nom: "Moto",
        img: "moto.webp",
        nomCreator: "LAMBERT Sophie",
        nbPieces: "180",
        price: "28",
        fav: true,
    },
    navette: {
        nom: "Navette",
        img: "navette.webp",
        nomCreator: "DUBOIS Maxime",
        nbPieces: "450",
        price: "42",
        fav: false,
    },
    perroquet: {
        nom: "Perroquet",
        img: "perroquet.webp",
        nomCreator: "GARCIA Théo",
        nbPieces: "130",
        price: "20",
        fav: false,
    },
    renard: {
        nom: "Renard",
        img: "renard.jpg",
        nomCreator: "LEFEBVRE Camille",
        nbPieces: "110",
        price: "17",
        fav: false,
    },
    tigre: {
        nom: "Tigre",
        img: "tigre.webp",
        nomCreator: "ROUSSEAU Marc",
        nbPieces: "250",
        price: "35",
        fav: false,
    }
};